export const TOOL_LABELS: Record<string, [string, string]> = {
  record_observation: ['Recording observation', 'Recorded observation'],
  recall: ['Searching memory', 'Searched memory'],
  create_tag: ['Creating tag', 'Created tag'],
  update_tag_description: ['Updating tag', 'Updated tag'],
  list_tags: ['Reviewing tags', 'Reviewed tags'],
  memory_stats: ['Checking memory', 'Checked memory'],
  web_fetch: ['Reading web page', 'Read web page'],
  web_post: ['Sending request', 'Sent request'],
  lists_catalog: ['Checking lists', 'Checked lists'],
  list_create: ['Creating list', 'Created list'],
  list_read: ['Reading list', 'Read list'],
  list_add: ['Adding to list', 'Added to list'],
  list_supersede: ['Updating item', 'Updated item'],
  list_archive: ['Archiving item', 'Archived item'],
  list_documents: ['Checking documents', 'Checked documents'],
  read_document: ['Reading', 'Read a passage'],
  current_time: ['Checking time', 'Checked time'],
  chatroom_post: ['Posting to chatroom', 'Posted to chatroom'],
  chatroom_read: ['Reading chatroom', 'Read chatroom'],
  chatroom_search: ['Searching chatroom', 'Searched chatroom'],
  check_budget: ['Checking budget', 'Checked budget'],
  schedule_wakeup: ['Scheduling wake-up', 'Scheduled wake-up'],
  check_wakeup: ['Checking wake-up', 'Checked wake-up'],
  cancel_wakeup: ['Cancelling wake-up', 'Cancelled wake-up'],
  set_cadence: ['Setting cadence', 'Set cadence'],
  get_cadence: ['Checking cadence', 'Checked cadence'],
  wall_pin: ['Pinning to wall', 'Pinned to wall'],
  wall_unpin: ['Unpinning from wall', 'Unpinned from wall'],
  wall_read: ['Reading wall', 'Read wall'],
  run_code: ['Running code', 'Ran code'],
  save_script: ['Saving script', 'Saved script'],
  run_script: ['Running script', 'Ran script'],
  list_scripts: ['Listing scripts', 'Listed scripts'],
  delete_script: ['Deleting script', 'Deleted script'],
  send_delivery: ['Sending delivery', 'Sent delivery'],
  random_words: ['Generating random words', 'Generated random words'],
  propose_agent: ['Proposing agent', 'Proposed agent'],
  approve_agent: ['Approving agent', 'Approved agent'],
  list_proposals: ['Checking proposals', 'Checked proposals'],
  x402_buy: ['Processing x402 payment', 'Processed x402 payment'],
  x402_check: ['Checking x402 endpoint', 'Checked x402 endpoint'],
  track_service: ['Tracking service', 'Tracked service'],
  list_services: ['Listing services', 'Listed services'],
  dm_read: ['Reading DMs', 'Read DMs'],
  dm_send: ['Sending DM', 'Sent DM'],
  github_post_issue: ['Posting GitHub issue', 'Posted GitHub issue'],
  github_post_comment: ['Posting GitHub comment', 'Posted GitHub comment'],
}
