export const TOOL_LABELS: Record<string, [string, string]> = {
  record_observation: ['Recording observation', 'Recorded observation'],
  recall: ['Searching memory', 'Searched memory'],
  create_tag: ['Creating tag', 'Created tag'],
  update_tag_description: ['Updating tag', 'Updated tag'],
  list_tags: ['Reviewing tags', 'Reviewed tags'],
  memory_stats: ['Checking memory', 'Checked memory'],
  web_fetch: ['Reading web page', 'Read web page'],
  lists_catalog: ['Checking lists', 'Checked lists'],
  list_create: ['Creating list', 'Created list'],
  list_read: ['Reading list', 'Read list'],
  list_add: ['Adding to list', 'Added to list'],
  list_supersede: ['Updating item', 'Updated item'],
  list_archive: ['Archiving item', 'Archived item'],
  list_documents: ['Checking documents', 'Checked documents'],
  read_document: ['Reading', 'Read a passage'],
  current_time: ['Checking time', 'Checked time'],
  chatroom_post: ['Posting to chatroom', 'Posted to chatroom'],
  chatroom_read: ['Reading chatroom', 'Read chatroom'],
  check_budget: ['Checking budget', 'Checked budget'],
  schedule_wakeup: ['Scheduling wake-up', 'Scheduled wake-up'],
  check_wakeup: ['Checking wake-up', 'Checked wake-up'],
  cancel_wakeup: ['Cancelling wake-up', 'Cancelled wake-up'],
}
